export const ADD_PRODUCT = 'ADD_PRODUCT';
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
export const ADD_PRODUCT_ERROR = 'ADD_PRODUCT_ERROR';

export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_ERROR = 'GET_PRODUCTS_ERROR';

export const GET_DELETE_PRODUCT = 'GET_DELETE_PRODUCT';
export const GET_DELETE_PRODUCT_SUCCESS = 'GET_DELETE_PRODUCT_SUCCESS';
export const GET_DELETE_PRODUCT_ERROR = 'GET_DELETE_PRODUCT_ERROR';
